#!/bin/sh

##### Setup diff-so-fancy Tool ####################################################

if [ ! -e "${HOME}/bin/diff-so-fancy" ]; then
  curl -sLo "${HOME}/bin/diff-so-fancy" \
            "https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy"
  chmod +x "${HOME}/bin/diff-so-fancy"
fi
