#!/bin/sh

##### Setup Speedtest Tool ####################################################

if [ ! -e "${HOME}/bin/speedtest-cli" ]; then
  curl -sLo "${HOME}/bin/speedtest-cli" \
            "https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py"
  chmod +x "${HOME}/bin/speedtest-cli"
fi
